foreground   #d8d2c7
background   #16080a
cursor       #d8d2c7

color0       #16080a
color8       #97938b
color1       #C46E4C
color9       #C46E4C
color2       #788663
color10      #788663
color3       #AA9166
color11      #AA9166
color4       #CA9D6C
color12      #CA9D6C
color5       #D5C172
color13      #D5C172
color6       #D2B28D
color14      #D2B28D
color7       #d8d2c7
color15      #d8d2c7
