# The basic colors
foreground              #ffffff
background              #0a0a0a
selection_foreground    #0a0a0a
selection_background    #ffffff

# Cursor colors
cursor                  #ffffff
cursor_text_color       #cd3131

# kitty window border colors
active_border_color     #e7e7e7
inactive_border_color   #414140

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #3a3d41
inactive_tab_foreground #858485
inactive_tab_background #1e1e1e

# black
color0 #0a0a0a
color8 #606266

# red
color1 #da5858
color9 #e36d6d

# green
color2  #3fc661
color10 #61d67e

# yellow
color3  #e8ca5e
color11 #fadd75

# blue
color4  #497ee9
color12 #5d8dee


# magenta
color5  #d56cc3
color13 #df81cf


# cyan
color6  #5cd8e6
color14 #7eeaf6

# white
color7  #ffffff
color15 #e0e0e1
