[FileDialog]
history=file:///home/cattette/Documents/PDXmodding/EU5, file:///home/cattette/Pictures/pfp, file:///home/cattette/Documents/webtest/images/maps, file:///home/cattette/Documents/webtest/images, file:///home/cattette/Documents/cattette-website/site/images/maps
lastVisited=file:///home/cattette/Documents/cattette-website/site/images/maps
qtVersion=6.11.1
shortcuts=file:, file:///home/cattette
sidebarWidth=98
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
