#!/bin/bash
# rofi -show bl -modes "bl:./rofi-bluetooth"
if [ "$@" = "FiiO" ]
then
    i3-msg exec ~/dotfiles/.config/rofi-utils/bluetooth/bt-toggle.sh 40:ED:98:1A:3E:E2
fi
if [ x"$@" = x"CX Plus" ]
then
    i3-msg exec ~/dotfiles/.config/rofi-utils/bluetooth/bt-toggle.sh 80:C3:BA:37:DC:1F
fi

if [ x"$@" = x"quit" ]
then
    exit 0
fi
echo "FiiO"
echo "CX Plus"
echo "quit"
