#!/bin/bash
# rofi -show bl -modes "bl:./rofi-bluetooth"
devtoggle() {
  device="$1"
  if bluetoothctl info "$device" | grep 'Connected: yes' -q; then
    bluetoothctl disconnect "$device"
  else
    bluetoothctl connect "$device"
  fi
}
if [ "$@" = "FiiO" ]
then
    devtoggle 40:ED:98:1A:3E:E2
fi
if [ x"$@" = x"CX Plus" ]
then
    devtoggle 80:C3:BA:37:DC:1F
fi

if [ x"$@" = x"quit" ]
then
    exit 0
fi
echo "FiiO"
echo "CX Plus"
echo "quit"
