#!/bin/bash

URL="$1"
ALBUM="$2"

mkdir /run/media/cattette/ssd512/Music/"$ALBUM"

yt-dlp -x -o "%(fulltitle)s" -P /run/media/cattette/ssd512/Music/"$ALBUM" $URL

notify-send -t 1500 "Music downloaded successfully"

exit 0
