# GODOT

# You can use nc if you prefer
[language-server.godot]
command = "socat"
args = ["STDIO", "TCP:127.0.0.1:6005"]

# gdformat via pip install gdtoolkit
[[language]]
name = "gdscript"
language-servers = ["godot"]
formatter = { command = "gdformat", args = ["-"] }
auto-format = true

[[language]]
name = "html"
language-servers = [{ name = "superhtml", except-features = ["format"] }, "vscode-html-language-server"]
auto-format = true

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

# Inline configuration is also supported
# https://biomejs.dev/blog/biome-v2-4/#editor-inline-configuration
[language-server.biome.config.biome.inlineConfig]
linter.rules.suspicious.noConsole = "off"

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
